version: '3.1'

services:
  db:
    container_name: db_container
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: gaga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432